### ISSUE TITLE
Criar rota de detalhe do OA sem percentuais

### ISSUE THREAD

**Issue by dviniciusbonin** [Farma-Authoring-Tool/farma-api#64]
Criar rota de detalhe do OA retornando o seguinte payload: 

```
{
	"id": 1,
	"title": "Objeto de aprendizagem teste",
	"description": "descrição teste",
	"pages": [
		{
			"type": "Introduction",
			"title": "intro 2",
			"position": 1711678342,
			"description": "conteudo introducao 2",
			"status": "viewed"
		},
		{
			"type": "Exercise",
			"title": "exercicio 1",
			"position": 1711678346,
			"description": "teste exercicio 1",
			"status": "not_viewed",
			"solution_steps": [
				{
					"position": 1711678349,
					"status": "viewed",
					"attempts": 6
				}
			]
		}
	],
	"page": {
		"type": "Introduction",
		"title": "intro 2",
		"position": 1711678342,
		"description": "conteudo introducao 2",
		"status": "viewed"
	},
	"progress": {
		"completed": 75,
		"explored": 80,
		"unexplored": 20
	}
}
```
Para valores de percentuais retornar valores fake nesse primeiro momento

Cenários de teste, verificar se:
- Retorna a primeira página corretamente
-  Retornando as páginas corretas
- Se usuário professor, retornar apenas se o lo foi cadastrado por ele

**Comment by MarczalTSIGP** [comment]
@dviniciusbonin para qual visualização é essa rota? Aluno, professor, guest?

**Comment by MarczalTSIGP** [comment]
Fiz a revisão e refatoração da sua PR, veja as modificações em https://github.com/Farma-Authoring-Tool/farma-api/pull/66/commits/44f040c73ad94f2ca6e4656109b32a4c5710a089 

Comentários:
O user pode ser tanto professor quando aluno, não existe diferença de perfil no sistema, tanto usuário pode criar e compartilhar OA, quando pode acessar OAs por meio das turmas.

Para qual visualização é esse OA que está construindo? Considerei que seria para o aluno matriculado em uma turma, um OA disponível para interação com o aluno.

Fiz diversas refatorações, estude elas e me pergunte se não enteder.

Termine os testes fazendo a verificação do soluction_steps and tips.

OBS: Seu teste não testava o retorno, se tivesse algum problema no json de retorno nunca saberia, o retorno a ser verificado deve ficar explicito no teste. Usando a classe que fez, poderia remover ou adicionar atributos ou até mesmo se ela montasse errado os atributos, você nunca saberia.

Também atualizei a versão do ruby para 3.3.0 e o rails para 7.1.2
